# Makefile generated by gb: http://go-gb.googlecode.com
# gb provides configuration-free building and distributing

include $(GOROOT)/src/Make.inc

TARG=gorf
GOFILES=\
	dscan.go\
	field.go\
	global.go\
	gorf.go\
	pkg.go\
	rename.go\
	rewrite.go\
	scan.go\
	undo.go\
	util.go\

include $(GOROOT)/src/Make.cmd
